name: Build API Container

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/build-api-container.yaml"

jobs:
  build-api-container:
    runs-on: ubuntu-latest
    environment: personal_projects
    defaults:
      run:
        working-directory: api
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: leetdavid/starrail-automation-api:latest
